In [1]:
import pandas as pd

- id — pengidentifikasi pengguna unik.
- sex — jenis kelamin (0 = tidak ditentukan, 1 = perempuan, 2 = laki-laki).
- bdate — tanggal lahir .
- has_photo — apakah foto profil sudah terpasang (0 = belum terpasang, 1 = terpasang).
- has_mobile — apakah nomor telepon diketahui (0 = tidak diketahui, 1 = diketahui).
- city — kota.
- followers_count — jumlah pelanggan.
- graduation — tahun kelulusan.
- education_form — bentuk pendidikan.
- relation — status perkawinan (1 - belum menikah; 2 - punya teman/punya pacar; 3 - bertunangan/bertunangan; 4 - menikah; 5 - semuanya rumit;6 — dalam pencarian aktif; 7 - jatuh cinta; 8 - berpasangan; 0 - tidak ditentukan).
- education_status — status pelatihan.
- langs — daftar bahasa yang digunakan pengguna
- last_seen — waktu kunjungan terakhir.
- occupation_type —pekerjaan pengguna saat ini (sekolah, universitas, pekerjaan).
- occupation_name — nama organisasi.
- life_main — hal utama dalam hidup. (1 - keluarga dan anak-anak; 2 - karier dan uang; 3 - hiburan dan relaksasi; 4 - sains dan penelitian;5 - perbaikan dunia; 6 - pengembangan diri; 7 - keindahan dan seni; 8 - ketenaran dan pengaruh). 
- people_main -karakteristik yang utama bagi orang. (1 - kecerdasan dan kreativitas; 2 - kebaikan dan kejujuran; 3 - kecantikan dan kesehatan; 4 - kekuasaan dan kekayaan; 5 - keberanian dan ketekunan; 6 - humor dan cinta hidup).
- career_start — tahun mulai bekerja.
- career_end — tahun berakhirnya pekerjaan.
- result — apakah pengguna membeli kursus pemrograman (0 —tidak, 1 — ya).

In [2]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

In [3]:
df_train

,id,sex,bdate,has_photo,has_mobile,followers_count,graduation,education_form,relation,education_status,langs,life_main,people_main,city,last_seen,occupation_type,occupation_name,career_start,career_end,result
0,64100,2,23.4.1990,1,1.0,150.0,2012.0,Full-time,2.0,Student (Specialist),Русский;English,0,0,Kaliningrad,2020-08-19 20:47:43,university,"БФУ им. Канта (бывш. РГУ им. Канта, КГУ)",False,False,0
1,46851,2,11.4,0,1.0,92.0,2011.0,Distance Learning,4.0,Alumnus (Specialist),Русский,0,0,NaN,2020-12-25 10:31:53,university,ЛНУ (бывш. ЛНПУ) им. Тараса Шевченко,False,False,0
2,13159,2,5.10,0,1.0,62.0,2012.0,Full-time,0.0,Alumnus (Specialist),Русский,0,6,Mogilev,2020-03-06 03:37:47,university,"БРУ (бывш. МГТУ, ММИ)",False,False,0
3,59148,1,1.3.1967,0,1.0,179.0,1989.0,Full-time,4.0,PhD,Русский,False,False,Moscow,2020-10-10 18:06:27,university,Bodø Graduate School of Business,False,False,0
4,46429,2,NaN,0,1.0,74.0,2008.0,Full-time,7.0,Alumnus (Specialist),Русский,3,2,Ryazan,2020-01-03 03:34:09,university,"РГРТУ (бывш. РГРТА, РРТИ)",False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8188,70625,1,17.11.1987,0,1.0,75.0,2013.0,Part-time,0.0,Student (Bachelor's),Русский,6,2,Moscow,2020-08-25 08:58:42,university,МСПИ (МОСПИ),False,False,0
8189,29009,2,NaN,0,1.0,726.0,0.0,Full-time,0.0,Alumnus (Bachelor's),Русский,0,0,Saint Petersburg,2020-03-28 02:25:55,university,СПбГТИ (ТУ),False,False,0
8190,62607,1,NaN,1,1.0,448.0,2008.0,Full-time,0.0,Alumnus (Bachelor's),Русский,0,6,Karaganda,2020-01-28 11:01:26,work,ТОО Eurasian Machinery,2010,False,1
8191,48342,2,NaN,1,1.0,2063.0,2025.0,Distance Learning,1.0,Alumnus (Specialist),Русский;English,6,6,Moscow,2020-07-01 16:40:54,work,Ремонт компьютеров и ноутбуков,2010,False,0
8192,67435,2,6.2.1986,0,1.0,876.0,2008.0,Full-time,4.0,Student (Master's),Русский;English,0,0,NaN,2020-09-27 01:00:11,work,Агентство MUZA | MUZA.agency,2014,False,1

In [4]:
df_train.drop(['bdate', 'has_photo', 'id', 'followers_count', 'langs', 'last_seen', 'city', 'career_start', 'career_end', 'occupation_name'], axis=1, inplace=True)
df_test.drop(['bdate', 'has_photo', 'followers_count', 'langs', 'last_seen', 'city', 'career_start', 'career_end', 'occupation_name'], axis=1, inplace=True)

In [5]:
def fill_education_form(education):
    if education == 'Full-time':
        return 1
    elif education == 'Distance Learning':
        return 2
    elif education == 'Part-time':
        return 3
    else:
        return 0
 
df_train['education_form'] = df_train['education_form'].apply(fill_education_form)
df_test['education_form'] = df_test['education_form'].apply(fill_education_form)

In [6]:
def fill_education_status(status):
    if status == 'Undergraduate applicant':
        return 1
    elif status == "Student (Bachelor's)":
        return 2
    elif status == "Alumnus (Bachelor's)":
        return 3
    elif status == "Student (Master's)":
        return 4
    elif status == "Alumnus (Master's)":
        return 5
    elif status == 'Student (Specialist)':
        return 6
    elif status == 'Alumnus (Specialist)':
        return 7
    elif status == 'Candidate of Sciences':
        return 8
    elif status == 'PhD':
        return 9
    else:
        return 0  # jika nilainya kosong atau tidak dikenal

df_train['education_status'] = df_train['education_status'].apply(fill_education_status)
df_test['education_status'] = df_test['education_status'].apply(fill_education_status)

In [7]:
def fill_occupation_type(x):
    if x == 'university':
        return 1
    elif x == 'work':
        return 2
    else:
        return 0
 
df_train['occupation_type'] = df_train['occupation_type'].apply(fill_occupation_type)
df_test['occupation_type'] = df_test['occupation_type'].apply(fill_occupation_type)

In [8]:
def fix_grad(data):
    nilai_tengah = data[(data > 1900) & (data < 3000)].median()
    return data.apply(lambda x: nilai_tengah if x <= 1900 or x >= 3000 else x)
df_train['graduation'] = fix_grad(df_train['graduation'])
df_test['graduation'] = fix_grad(df_test['graduation'])

In [9]:
convert_dtype = ['has_mobile', 'graduation', 'relation']
df_train[convert_dtype] = df_train[convert_dtype].astype(int)
df_test[convert_dtype] = df_test[convert_dtype].astype(int)

In [10]:
def clean_main_value(val):
    if val == False or val == 'False':  
        return 0
    try:
        return int(val)
    except:
        return 0  

df_train['life_main'] = df_train['life_main'].apply(clean_main_value)
df_test['life_main'] = df_test['life_main'].apply(clean_main_value)
df_train['people_main'] = df_train['people_main'].apply(clean_main_value)
df_test['people_main'] = df_test['people_main'].apply(clean_main_value)

-----------Model machine learning---------------

In [11]:
#1. import modul sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [12]:
#2. bagi data menjadi Data variabel(X) dan target(Y)
X_train = df_train.drop('result', axis = 1)
y_train = df_train['result']
X_test = df_test.drop('id', axis = 1)

In [13]:
#3. membuat data menjadi Nilai standar
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
#4. Membuat variabel model
# Support Vector Machine
svm_model = SVC()
# Naive Bayes
nb_model = GaussianNB()
# Random Forest
rf_model = RandomForestClassifier()

In [15]:
#5. melakukan training model
svm_model.fit(X_train, y_train)
nb_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [16]:
#6. Melakukan prediksi pada data Test
y_pred1 = svm_model.predict(X_test)
y_pred2 = nb_model.predict(X_test)
y_pred3 = rf_model.predict(X_test)

In [17]:
result = pd.DataFrame({'id' : df_test['id'], 'result': y_pred1})
result.to_csv('result_svm.csv', index = False)
result2 = pd.DataFrame({'id' : df_test['id'], 'result': y_pred2})
result2.to_csv('result_naivebayes.csv', index = False)
result3 = pd.DataFrame({'id' : df_test['id'], 'result': y_pred3})
result3.to_csv('result_randomforesst.csv', index = False)

In [18]:
df_train

,sex,has_mobile,graduation,education_form,relation,education_status,life_main,people_main,occupation_type,result
0,2,1,2012,1,2,6,0,0,1,0
1,2,1,2011,2,4,7,0,0,1,0
2,2,1,2012,1,0,7,0,6,1,0
3,1,1,1989,1,4,9,0,0,1,0
4,2,1,2008,1,7,7,3,2,1,0
...,...,...,...,...,...,...,...,...,...,...
8188,1,1,2013,3,0,2,6,2,1,0
8189,2,1,2011,1,0,3,0,0,1,0
8190,1,1,2008,1,0,3,0,6,2,1
8191,2,1,2025,2,1,7,6,6,2,0
8192,2,1,2008,1,4,4,0,0,2,1